name: Noarr matrix example test Win

on:
  push:
    paths:
    - 'noarr/**'
    - '.github/workflows/noarr_matrix_example_test_win.yml'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: [windows-latest]

    steps:
    - uses: actions\checkout@v2

    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{github.workspace}}\examples\matrix\build

    - name: Configure CMake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: powershell
      working-directory: ${{github.workspace}}\examples\matrix\build
      # Note the current convention is to use the -S and -B options here to specify source 
      # and build directories, but this is only available with CMake 3.13 and higher.  
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: cmake ${{github.workspace}}\noarr -DCMAKE_BUILD_TYPE=$Env:BUILD_TYPE

    - name: Build
      working-directory: ${{github.workspace}}\examples\matrix\build
      shell: powershell
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config $Env:BUILD_TYPE

    - name: Test
      working-directory: ${{github.workspace}}\examples\matrix\build\Debug
      shell: powershell
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: .\matrix.exe "rows" 10
